name:                rename-subtitle-files
version:             0.1.0.0
github:              "g-plane/rename-subtitle-files"
license:             MIT
author:              "Pig Fang"
maintainer:          "g-plane@hotmail.com"
copyright:           "2020 Pig Fang"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/rename-subtitle-files#readme>

dependencies:
- base >= 4.7 && < 5
- directory
- extra

library:
  source-dirs: src

executables:
  rename-subtitle-files-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rename-subtitle-files

tests:
  rename-subtitle-files-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - QuickCheck
    - rename-subtitle-files
