name: Build

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo build --release
      - uses: softprops/action-gh-release@v1
        with:
          files: ./target/release/rename-subtitle-files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
