name: Build

on: push

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build project
      run: stack build
    - name: Archive built artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: .stack-work/dist
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: stack test
